### ISSUE TITLE
[Orga] Check Branch Protection Rules

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/.github#2]
**Issue description in words**:
(What is the reason for creating the issue and what is it about)  
We want to ensure all pull-request get reviewed. 
 
**TODOS**: 
(In technical terms, suggestions of what has to be done to fix the issue.) 
-  Check how to introduce branch protection rules in github 
-  Check which repositories make sense for the rules 
-  Introduce the rules to the repositories 

**Acceptance-Criteria** 
(what shall be reached with this issue, these criteria are mandatory for closing the issue) 
-  Branch Rules in relevant repositories are set up 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project
- [x] code was merged to main/dev
- [x] feature branch has been deleted after merge to main/dev

**Comment by Hyper-Node** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by Hyper-Node** [comment]
docker-backup, docker-quickstatements have branch protection rules now 
portal-compose already had. 

can be changed in settings->branch->add-rules

**Comment by Hyper-Node** [comment]
Admins have to be included in branch protection rules, otherwise they can push to the main branches without review.

**Comment by Hyper-Node** [comment]
A emergency force push possibility would be nice.

**Comment by Hyper-Node** [comment]
Added guideline how to bypass bpr in emergency cases: 
https://github.com/MaRDI4NFDI/T5ProjectManagement/discussions/45
