### ISSUE TITLE
[Orga] Create Meeting Introduction Slides 

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/.github#4]
**Issue description in words**:
(What is the reason for creating the issue and what is it about)  
To be clear about the content of the meetings and the items within the meeting create some introduction slides which can be also displayed from time to time in the dailies. Also create short agenda note which is shown upfront the meeting somewhere visible
 
**TODOS**: 
(In technical terms suggestions what has to be done to fix the issue.) 
- Create introduction slide for combined meeting (Review, Retro, Planning) 
-  
-  
- 

**Acceptance-Criteria** 
(what shall be reached with this issue, these criteria are mandatory for closing the issue) 
- Slides created 
- Agenda added to be visible before meetings

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [x] Example fields have been removed
- [x] MaRDI_Project has been assigned as project
